# Generated by Django 3.2.8 on 2021-12-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211207_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['memorized']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='memorized',
        ),
    ]
